version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: table-to-kml-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    # Optional: mount logs directory
    volumes:
      - ./logs:/app/logs